### ISSUE TITLE
Real-Time Notifications not working when published to Azure

### ISSUE THREAD

**Issue by firnasz** [aspnetzero/documents#108]
I'm using INotificationPublisher.PublishAsync() method to push notifications from background job. This will be triggered in client side as follows;

`abp.event.on('abp.notifications.received', function (userNotification) {
    console.log(userNotification);
});`

The notification trigger in fontend properly works in localhost, but when published to Azure, it does not show any, until the page is reloaded. Any suggestion appreciated.

**Comment by hikalkan** [comment]
I suppose Azure requires additional configuration to make SignalR working. @ismcagdas do you know the solution?

**Comment by maliming** [comment]
May be related to this 
https://github.com/aspnetzero/aspnet-zero-core/issues/1426#issuecomment-405954104
https://docs.microsoft.com/en-us/aspnet/signalr/overview/deployment/using-signalr-with-azure-web-sites#enabling-websockets-on-azure-app-service-web-apps
