### ISSUE TITLE
The page is blank after login

### ISSUE THREAD

**Issue by AlanLang** [aspnetzero/documents#109]
version：6.2.0
The landing page is good，but Once I log into the system，there is noting in the page
![snipaste_2018-11-01_10-31-56](https://user-images.githubusercontent.com/33884749/47829263-723fa380-ddc1-11e8-8cb1-1ca5f06b52d6.png)
![snipaste_2018-11-01_10-33-06](https://user-images.githubusercontent.com/33884749/47829282-8b485480-ddc1-11e8-9a74-62ba97963bf9.png)

**Comment by maliming** [comment]
https://github.com/aspnetzero/aspnet-zero-core/issues/1855
