### ISSUE TITLE
Updating file value in Log4net.config doesn't change website logs path in Mantainence tab

### ISSUE THREAD

**Issue by OulaAlshiekh** [aspnetzero/documents#114]
I am using ASP.NET Boilerplate version 3.2.4.0 with Code-First Entity Framework with and MVC 5.
my Entity Frame work version is 6.2.0

In order to change logging path from default one which is

web/App_Data/Logs

which is added as the following property in log4net.config

i changed this property to be

and my logging output changed to be written on desired path on c:\Logs

but the problem that this change is not reflected to WebsiteLogs tab that is under Maintenance tab in Administration page

it still shows old data that is located in default path of log4.net file

How to reflect log4.net path change to the output of website logs tab too?

Is there any setting to set this change ?

**Comment by ismcagdas** [comment]
@OulaAlshiekh could you create the issue on https://github.com/aspnetzero/aspnet-zero-core/issues ?
