### ISSUE TITLE
error in Xamarin docs :PeopleView.xaml

### ISSUE THREAD

**Issue by HADDADENICAR** [aspnetzero/documents#122]
[HERE](https://docs.aspnetzero.com/documents/zero/latest/Developing-Step-By-Step-Xamarin#populating-people-view-with-data) in **PeopleView.xaml**:

you have commited an error, instead of : 

       xmlns:behaviors="clr-namespace:Acme.PhoneBookDeehaviors;assembly=Acme.PhoneBookDemo.Mobile.Shared"

it's :
    
    xmlns:behaviors="clr-namespace:Acme.PhoneBook.Behaviors;assembly=Acme.PhoneBookDemo.Mobile.Shared"

**Comment by ismcagdas** [comment]
Thanks a lot @HADDADENICAR
