### ISSUE TITLE
GetPeople is Synchronus NOT Asynchronus !!

### ISSUE THREAD

**Issue by HADDADENICAR** [aspnetzero/documents#123]
In [Asp.net Core & Angular docs](https://docs.aspnetzero.com/documents/zero/latest/Developing-Step-By-Step-Angular)
you have created the method **GetPeople** as a *Synchronus* method.
In[Xamarin docs](https://docs.aspnetzero.com/documents/zero/latest/Developing-Step-By-Step-Xamarin#implementing-app-service-methods) you used the same interface of the previous doc **IPersonAppService**  of the first doc , but you implemented it as an asynchronus method ??

That dosen't work, should i make changes to the interface ? and the method GetPeople is Synchronus in the **PersonAppService** ?? should i make it asynchronus ?

**Comment by ismcagdas** [comment]
Hi @HADDADENICAR,

Could you create this issues on https://github.com/aspnetzero/aspnet-zero-core or https://support.aspnetzero.com ?

**Comment by HADDADENICAR** [comment]
I don't have a paid account , so i can't . could you please answer me here

**Comment by ismcagdas** [comment]
Sure but if you don't have an account, how are you trying it ?

**Comment by HADDADENICAR** [comment]
I am a new worker, I haven't passed a month yet , they're testing me...
Only 2 old workers have a paid account, they gave me the project to see if
I can understand aspnetzero so I can do the business needs so I m still in
documentation phase.

**Comment by HADDADENICAR** [comment]
I tried to use **GetAllAsync()** method to resolve the problem but i find that you haven't implmented such method in the solution !  
what should i do  ?

**Comment by ismcagdas** [comment]
You can use sync version in the xamarin app and modify the code accordingly.

**Comment by HADDADENICAR** [comment]
I just asked the team for access to their paid account, but they told me that the number of question is limited to 5 and they already used 1  so they will use it only in urgent tasks.

As you said that i can use the synchronus version of **GetAll()**, i found in your support [a simlair issue](https://support.aspnetzero.com/QA/Questions/4410) about that. 
so i changed my  GetMethod as follow :

     var query = _personRepository
                .GetAll();
         
    var people = await AsyncQueryableExecuter.ToListAsync(query);

to make GetPeople an asynchronus method .

However the solution still dosen't work, and the problem comes from the ViewModel class :

     Castle.MicroKernel.ComponentActivator.ComponentActivatorException: ComponentActivator: could not instantiate Acme.PhoneBookDemo.Views.PeopleView


Why don't update the documentation ? 
and why your help is so limited  ?

**Comment by ismcagdas** [comment]
> Why don't update the documentation ?

@HADDADENICAR I just opened the issue so we will check and fix it.

> and why your help is so limited ?

Actually it is not limited. I don't know how your company go the idea of 5 questions but **there is no question limit at all**. There is only developer limit. 

So, please ask your company to contact with info@aspnetzero.com and we will grant you access for private repos and support website.

**Comment by alirizaadiyahsi** [comment]
Hi @HADDADENICAR I will update Asp.net Core & Angular docs to use async methods. You can use async methods (change interface to use async) for both. 

Your latest error seems not to related with async methods.

**Comment by alirizaadiyahsi** [comment]
https://github.com/aspnetzero/documents/commit/0389cda09b10206bc7f8c5e3623124ab2e4ef4bc

**Comment by HADDADENICAR** [comment]
@alirizaadiyahsi  so i showed download the last version.

actually i have made  many coding  , that  take more days to repeat it . can you tell me how to do it with Sync Method GetAll() please.

**Comment by ismcagdas** [comment]
@HADDADENICAR you can easily change sync GetPeople method to async. It shouldn't be that hard. Have you tried that ?

**Comment by HADDADENICAR** [comment]
@ismcagdas You are right it work in angular by changing it to async,, by adding the following changes :

         var query = _personRepository
                      .GetAll();
     
         var people = await AsyncQueryableExecuter.ToListAsync(query);

The Xamarin project still dosen't display the data, which made my  doubt.

**Comment by ismcagdas** [comment]
It might be related to something else if you are not getting any exception. You can check executed SQL Query using SQL profiler.

**Comment by HADDADENICAR** [comment]
@ismcagdas  i get and resolved the problem of xamarin [here](https://github.com/aspnetzero/documents/issues/129).
I passed now to filtering , so I need to know again how to make the GetPeople Method **async**, with just **GetAll()** that works, But with this code: 
  
     var query = _personRepository
           .GetAll()
            .WhereIf(
                !input.Filter.IsNullOrEmpty(),
                 p => p.Name.Contains(input.Filter) ||
                  p.Surname.Contains(input.Filter) ||
                 p.EmailAddress.Contains(input.Filter)
                  )
                .OrderBy(p => p.Name)
                .ThenBy(p => p.Surname)
                .ToList();

this line:
 
               await AsyncQueryableExecuter.ToListAsync<Person>(query);

 return an error:

    Impossible Conversion of 'System.Collections.Generic.List<Acme.PhoneBookDemo.PhoneBook.Person>'to' System.Linq.IQueryable<Acme.PhoneBookDemo.PhoneBook.Person>'

**Comment by acjh** [comment]
Remove `.ToList()`.

**Comment by HADDADENICAR** [comment]
@acjh the same issue remains even when i remove **.ToList()**

**Comment by acjh** [comment]
No, it doesn't.

**Comment by HADDADENICAR** [comment]
I tried that and i get the same issue , why do you say No ?

**Comment by acjh** [comment]
[`Queryable.ThenBy`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.queryable.thenby?view=netcore-2.2) returns an `IOrderedQueryable`, not a `List`.

**Comment by HADDADENICAR** [comment]
Removing **ToList()** i get the error below:

   Impossible Conversion of 'System.Linq.IOrderEnumerable<Acme.PhoneBookDemo.PhoneBook.Person>' to System.Linq.IQueryable<Acme.PhoneBookDemo.PhoneBook.Person>'

so it's not IOrderQueryable !

**Comment by HADDADENICAR** [comment]
But even after that the filter isn't working !

**Comment by HADDADENICAR** [comment]
Solved: 
i get help from a college , he just keep the header that make the function look ***async***, but the core is ***sync***:

             public async Task<ListResultDto<PersonListDto>> GetPeople(GetPeopleInput input)
        {

            var people = _personRepository
                               .GetAll()
                                .Include(p => p.Phones)
                                .WhereIf(
                                 !input.Filter.IsNullOrEmpty(),
                                     p => p.Name.Contains(input.Filter) ||
                                     p.Surname.Contains(input.Filter) ||
                                      p.EmailAddress.Contains(input.Filter)
                                      )
                                       .OrderBy(p => p.Name)
                                       .ThenBy(p => p.Surname);
                return new ListResultDto<PersonListDto>(ObjectMapper.Map<List<PersonListDto>>(people));
        }

so no need for async method , just the header ! , that's perfectly wiered lol.

**Comment by acjh** [comment]
> Removing **ToList()** i get the error below:
>
>> Impossible Conversion of 'System.Linq.IOrderEnumerable<Acme.PhoneBookDemo.PhoneBook.Person>' to System.Linq.IQueryable<Acme.PhoneBookDemo.PhoneBook.Person>'

Add `using Abp.Linq.Extensions;` instead of `using Abp.Collections.Extensions;`.

**Comment by acjh** [comment]
> and **.ToListAsync()** doesn't exist

Add `using Microsoft.EntityFrameworkCore;`
