### ISSUE TITLE
aspnet-zero-service-class-isnt-created-in-client-side-angular

### ISSUE THREAD

**Issue by HADDADENICAR** [aspnetzero/documents#124]
Can you answer please [this SO question](https://stackoverflow.com/questions/55157540/aspnet-zero-service-class-isnt-created-in-client-side-angular) ?

**Comment by ismcagdas** [comment]
Answered. If you are an AspNet Zero customer, please create such issues on https://github.com/aspnetzero/aspnet-zero-core or https://support.aspnetzero.com.
