### ISSUE TITLE
slow unit tests

### ISSUE THREAD

**Issue by yousufali** [aspnetzero/documents#130]
Hello guys,

In one of the applications I am working on, I noticed that .net core unit tests are taking good 7 -10 minutes to complete. I checked the phonebookappdemo and it is doing same, is there anything that we can do to improve time it takes to complete unit tests.

**Comment by maliming** [comment]
- What is your product version?
- What is your product type (Angular or MVC)?
- What is product framework type (.net framework or .net core)?

**Comment by yousufali** [comment]
It is 6.8, angular with .net core api, .net core.

 I have looked at the demo tests again. it is running in 1.5 mins, It is something in the codebase I am working on.

Please close this ticket.
