### ISSUE TITLE
Iconize issue in PersonDetailsView.xaml

### ISSUE THREAD

**Issue by HADDADENICAR** [aspnetzero/documents#132]
As it is mentionned [in your support](https://support.aspnetzero.com/QA/Questions/5863), **Xam.FormsPlugin.Iconize** isn't working and **Xam.Plugin.Iconize** take it place.

but it dosen't worked for me by just  changing that , i got this error :

      Application.Resources StaticResource not found for key
Searching a solution i found  [an answer to a similar issue ](https://forums.xamarin.com/discussion/31872/application-resources-staticresource-not-found-for-key) telling that we need to use  ***DynamicResource*** for global styles.

I didn't understood that , by i tried it  and the project run , so instead of : 

    <iconize:IconButton Margin="3"
                           .....
                            HeightRequest="{StaticResource SmallActionButtonSize}"
                            WidthRequest="{StaticResource SmallActionButtonSize}"
                   ....>
this is what works : 

       <iconize:IconButton Margin="3"
                           .....
                            HeightRequest="{DynamicResource SmallActionButtonSize}"
                            WidthRequest="{DynamicResource SmallActionButtonSize}"
                   ....>

**1-can you please explain me why this happen ?**

the issue didn't stop there the fontAwesome didn't worked for me too : 

running the project , i get the text ***fa-trash*** instead of the icon , after a lot of search i changed it to ***fas-trash*** and the icon appeared.

**2-can you tell me please where i can find the true name of icons ?**

**Comment by ismcagdas** [comment]
@HADDADENICAR it is nice that you find such problems but we can't provide support here as we mentioned before. As I mentioned earlier, AspNet Zero doesn't have any question limit on support website.

So, why don't you ask your company/team to add you to AspNet Zero's support website ?
At least, please send your AspNet Zero account username to info@aspnetzero.com and we will handle the rest for you.

**Comment by HADDADENICAR** [comment]
@ismcagdas  you may find it weired but i just demand the access , and this was the response of the cheif:

> suppose we don't have support , what would you do ? use Google 

I understand that they don't trust me , since i am still new , anyway  sorry for spamming the Github docs with question for support , i will use google more than questionning since they don't trust me yet , Thanks.

**Comment by ismcagdas** [comment]
> suppose we don't have support , what would you do ? use Google

The answer to that question is https://stackoverflow.com/, more specifically https://stackoverflow.com/questions/tagged/aspnetboilerplate. As you can understand that sentence is silly because AspNet Zero is a paid product and the support is part a part of AspNet Zero which our customers pay for.

We need to understand if you are using AspNet Zero legally or not.
So, at least learn the username of your Company's AspNet Zero account and share it with info@aspnetzero.com. 

If you can't do that, please use https://stackoverflow.com/ instead of this repository.
