### ISSUE TITLE
Extending Abstract Entites/(".Web\App\common\views\users\index.js") not found

### ISSUE THREAD

**Issue by HADDADENICAR** [aspnetzero/documents#134]
I post this issue here, because i think that there is missing informations in your [documentation](https://docs.aspnetzero.com/documents/aspnet-core-angular/latest/Extending-Existing-Entities);

in **Show Address in the UI** section, you describe some actions  under this path =>" .Web\App\common\views\users\index.js", which it dosen't exist in your solution **\*.Web.Host** ,**\*Web.Core** or **\*Web.Core**.

I see that this section is for both  MVC & Angular projects, but i think the documentation is describing only the MVC uses case !

**Comment by ismcagdas** [comment]
The client side part of this document is written for ASP.NET MVC 5.x version of AspNet Zero. We will write the new version of this document for ASP.NET Core versions. This issue is tracked internally, so closing because of that.

Thanks anyway for reporting it.
