### ISSUE TITLE
When trying to send notification to subscribed users on a specific permission it only works when this permission is global not on permissions assigned to tenant

### ISSUE THREAD

**Issue by amr-saafan** [aspnetzero/documents#22]
Hello,

When trying to add a notification with a tenant permission it doesn't work.. only works with host's permission... is there a fix to that?

Thanks,
Amr Saafan
http://www.nilebits.com/

**Comment by ismcagdas** [comment]
moved to https://github.com/aspnetzero/aspnet-zero-core/issues/386.

**Comment by amr-saafan** [comment]
Hello @ismcagdas ,

How can I follow up with this issue?

Thanks,
Amr Saafan
http://www.nilebits.com/

**Comment by ismcagdas** [comment]
Hi @amr-saafan, you can follow the one I mentioned above.
We will work on this in a short time.

**Comment by amr-saafan** [comment]
He @ismcagdas ,

I have no access to https://github.com/aspnetzero/aspnet-zero-core/issues/386

Thanks,
Amr Saafan
http://www.nilebits.com/

**Comment by ismcagdas** [comment]
You are invited to private repositories.
You will be able to see it if you accept github invitation.

Thanks.

**Comment by alirizaadiyahsi** [comment]
Hi @amr-saafan,

I can't reproduce your issue. Is that possible to share your codes to understand what is wrong?

If you have permission to access this issue https://github.com/aspnetzero/aspnet-zero-core/issues/386, we can continue from here.
