### ISSUE TITLE
help authoring tool?

### ISSUE THREAD

**Issue by KasimMB** [aspnetzero/documents#28]
Hi @hikalkan 
could i know what tool you are using or prefer to write the documentation / user guide?

**Comment by alirizaadiyahsi** [comment]
We are mostly using Microsoft Expression Web 4. But there are developers who use other tools they are comfortable with in our team.

**Comment by KasimMB** [comment]
Thanks a lot @alirizaadiyahsi

**Comment by KasimMB** [comment]
Hi @alirizaadiyahsi ,
I have one more question pls, 
I downloaded the documentation files of this repository and open it via Expression web 4, I found the pages are stand alone and its not styled as the main website and does not contains the table of contents in each page, So how do you merge/embed the documents files into the main front-end website when you publish it?

**Comment by alirizaadiyahsi** [comment]
Table of contents are automatically creating (by using `h3` tags). This html pages are running as partial views. They are styled by layout page.

**Comment by KasimMB** [comment]
Thank you very much @alirizaadiyahsi
