### ISSUE TITLE
Sweetalert url is not working  

### ISSUE THREAD

**Issue by Sampath-Lokuge** [aspnetzero/documents#3]
Hi,
Sweetalert url is not working on the below mentioned doc.Please see that.Thanks. 

**[Javascript Message API](http://aspnetboilerplate.com/Pages/Documents/Javascript-API/Message)**

**Comment by hikalkan** [comment]
It's working for us. What's the problem? Where it does not work?

**Comment by Sampath-Lokuge** [comment]
The sweetalert url on this section : 

> Message API is implemented using sweetalert by default.

**Comment by Sampath-Lokuge** [comment]
This is the url which it's not working :

http://tristanedwards.me/sweetalert

**Comment by Sampath-Lokuge** [comment]
![Error]([img]http://i.imgur.com/4mAhetb.png[/img])

**Comment by hikalkan** [comment]
Have you added abp.sweetAlert.js in your layout?

**Comment by Sampath-Lokuge** [comment]
Yes,It is working on my app.The problem is on the above mentioned doc.

 ![Error](http://i.imgur.com/4mAhetb.png)

**Comment by hikalkan** [comment]
Try this: http://t4t5.github.io/sweetalert/

**Comment by hikalkan** [comment]
OK, fixed in the documents. Thanks.
