### ISSUE TITLE
version 5 of aspnetzero, jquery updates, datatable edit inline

### ISSUE THREAD

**Issue by MDSNet2016** [aspnetzero/documents#31]
I am trying to use the inline edit option of datatable. as I figure out in the new release of aspnetzero project, the jquery object of datatable is obsolete and the new release of data table which is configurable with dataTables.editor.js does not exist in the project.

I tried to upgrade it through NPM but I cannot find the name of this datatable jquery library in package.json, it doesn't exist.
it seems that for using this new library I should upgrade the principal jquery as well to the latest version, but doing this maybe I loose some other functionalities of metronics.
would you please help me by showing me a road map to upgrade java script stack to the newer version!?
actually i expected to find the latest version of jquery objects in the new metronics project. but it is still the old one.

**Comment by hikalkan** [comment]
Moved to https://github.com/aspnetzero/aspnet-zero-core/issues/643
