### ISSUE TITLE
Action menu does not disappear on routing to different html page

### ISSUE THREAD

**Issue by olexandrman** [aspnetzero/documents#35]
I have the same issue https://forum.aspnetboilerplate.com/viewtopic.php?f=5&t=9981. You wrote related link  https://github.com/aspnetzero/aspnet-ze ... issues/430 which does not work. I have 4.0 version of abp-zero-template with angular 4. When this issue will be fixed? Thanks.

**Comment by acjh** [comment]
It's already fixed. You can upgrade to v4.6.1.

**Comment by olexandrman** [comment]
Great. How can I update my project or simply add updates (about this issue) that I need without big changes?

**Comment by acjh** [comment]
You can try making this change: [`4768ce0`](https://github.com/aspnetzero/aspnet-zero-core/commit/4768ce025274c11125ffeb5a2327326d50a40aab#diff-3dbff79f8c92647aa5d806b69ea8e793)

How to migrate existing solution: https://github.com/aspnetzero/aspnet-zero/issues/96#issuecomment-268093697

**Comment by olexandrman** [comment]
These links do not work.

**Comment by acjh** [comment]
You can invite yourself here: https://aspnetzero.com/LicenseManagement
