### ISSUE TITLE
Devextrem Implemntation

### ISSUE THREAD

**Issue by AnwarRahahleh** [aspnetzero/documents#48]
Hi,

how can i can use DevExtreme into aspnetcore project ?

regards,anwar

**Comment by alirizaadiyahsi** [comment]
There is an article [HERE](https://medium.com/volosoft/devextreme-asp-net-zero-integration-444ea26d0fc5)

And these is the examples that are related above article:

https://github.com/aspnetzero/aspnet-zero-samples/tree/master/DevExpressDemo-ASPNETCore
https://github.com/aspnetzero/aspnet-zero-samples/tree/master/DevExtremeDemo-Angular
https://github.com/aspnetzero/aspnet-zero-samples/tree/master/DevExtremeDemo-JQuery
