### ISSUE TITLE
Application Crashes when excluding/unchecking Create User Interface 

### ISSUE THREAD

**Issue by valuewholesale** [aspnetzero/documents#52]
I know the tool is still new and so far it is working out well!  

However, when trying to create an entity for a relationship table that does not need an interface, the application crashes.  See attached for error.

Project Type: AspNetZeroCore | v5.1.0 | Core 2.0
`MultiTenancyEnabled = false;`

![capture-001](https://user-images.githubusercontent.com/29978553/36480108-184102e8-16d9-11e8-995b-0d79b7cb6ee0.JPG)
![capture-002](https://user-images.githubusercontent.com/29978553/36480109-184c6796-16d9-11e8-8933-08df19f26431.JPG)
![capture-error](https://user-images.githubusercontent.com/29978553/36480110-1856d6c2-16d9-11e8-9ebb-1ab30db338a9.JPG)

**Comment by valuewholesale** [comment]
Upgraded to version 1.2.3 and now only receive message "Entity is being generated" (attached)

![capture](https://user-images.githubusercontent.com/29978553/36480474-73f245ec-16da-11e8-8370-6b492d16943b.JPG)

**Comment by yekalkan** [comment]
Thanks for reporting! We've fixed it and released 1.2.4 version.

**Comment by valuewholesale** [comment]
@yekalkan 

Upgraded to 1.2.4 - programming error occurred in DTO generation (see attached).  I corrected manually but for future generating

![capture](https://user-images.githubusercontent.com/29978553/36482271-c1f5446e-16e0-11e8-855f-0e661b89233d.JPG)

![capture-001](https://user-images.githubusercontent.com/29978553/36482272-c2010434-16e0-11e8-842e-0761f0838703.JPG)

**Comment by yekalkan** [comment]
That probably happens when you don't set any property for create/edit form. We'll also fix that. Thanks again!

**Comment by valuewholesale** [comment]
Makes sense.

Thanks for the quick response!
