### ISSUE TITLE
Upgrading versions AspNetZero Project

### ISSUE THREAD

**Issue by valuewholesale** [aspnetzero/documents#53]
As of right now, I have a project in .NET Core using aspnetzero project version v5.1.

I noticed v5.2. has been released while my license is still active.

Is there any documentation on the best way to upgrade to the latest project version to get all major bug fixes and recent updates?   Does a new project have to be created then everything copied over?  

Is there a recommended process?

**Comment by hikalkan** [comment]
Hi,

Please see these;

1. https://forum.aspnetboilerplate.com/viewtopic.php?f=5&t=2486#p5511
2. https://github.com/aspnetzero/aspnet-zero/issues/96#issuecomment-185281191

**Comment by valuewholesale** [comment]
Thank you very much.  Point number 2 was helpful.  This can be closed.
