### ISSUE TITLE
RAD Tool Application Shared Input Files

### ISSUE THREAD

**Issue by valuewholesale** [aspnetzero/documents#54]
I noticed the tool is generating an input class file (i.e. CreateOrUpdateCountryInput.cs) and inside of there it is listing out all of the fields in the table rather than using the Dto.  See images for a few examples.  

1. Default template structure example:
![capture-001](https://user-images.githubusercontent.com/29978553/36551032-a92601a0-17c4-11e8-89b6-12628ce38863.JPG)

2. RAD Generated example:

![capture-countryu](https://user-images.githubusercontent.com/29978553/36551068-be7f9246-17c4-11e8-9130-23530ef6ae7c.JPG)

3. What I expected to be generated:
![capture-countrye](https://user-images.githubusercontent.com/29978553/36551469-9ce3c548-17c5-11e8-9f7d-f889be3992b6.JPG)

a) Was this done on purpose?  
b) Why is the name of the class differing from the filename in example no. 2 when generated?
c) Is there a reason that the Get[...]ForEditOutput.cs file is not generated either?

**Comment by yekalkan** [comment]
What goes wrong here is just naming. "CreateOrEditXDto" class is inside "CreateOrEditXInput". We'll correct it. Thanks for reporting!

wrong repository btw.

**Comment by valuewholesale** [comment]
@yekalkan 
Thanks.  

Can you point me in the direction of the repo for the rad tool?  

Also, could you clarify what you mean by the class is inside of the input file?  Are you just going to be separating them?

**Comment by ismcagdas** [comment]
@valuewholesale the repository of RAD tool is not open to customers currently.

**Comment by yekalkan** [comment]
@valuewholesale i mean file name is wrong.

**Comment by valuewholesale** [comment]
@yekalkan I agree the file name is wrong but that is minor.  

But don't you agree that there should be an input file that then has the DTO listed within rather than  having each field typed out in the input/edit class and in the DTO?   

![capture](https://user-images.githubusercontent.com/29978553/36730100-34645082-1b94-11e8-89a9-bfa66ea06cf3.JPG)

**Comment by yekalkan** [comment]
Of course it could be. But we did it this way. Next release dto's will be reviewed.

**Comment by ringsborg** [comment]
Are you planning on sharing the code for RAD at some point? Would be quite interesting...

**Comment by valuewholesale** [comment]
@ringsborg see answer https://github.com/aspnetzero/aspnet-zero-core/issues/644#issuecomment-362383023

**Comment by yekalkan** [comment]
@ringsborg We have re-designed the template system and will release it in a short time. It will allow you to modify existing templates completely and creating new ones.

**Comment by ringsborg** [comment]
@valuewholesale @yekalkan thank you! ;)

**Comment by valuewholesale** [comment]
One more thing to note while we are on this topic.  Can a property type of Decimal be added?  Double properties are going into database as type float which are not as precise as a decimal.

**Comment by valuewholesale** [comment]
@yekalkan Since the repository for RAD tool is not open to public can I suggest one more thing on here?

The Multi-Tenancy option on the RAD tool is requiring either Host or Tenant or both to be selected.  In my case where multi tenancy is disabled, I am choosing only "Host" so a TenantId is not added to the table.  I then go to App Authorization provider and remove MultiTenancySide from create child permission (i.e. move it into common permissions).

**Comment by yekalkan** [comment]
@valuewholesale thanks for reporting. We'll fix it.

**Comment by yekalkan** [comment]
@valuewholesale By the way, You can check both host and tenant if multi-tenancy is disabled, then you won't have to remove or add anything.

**Comment by valuewholesale** [comment]
@yekalkan  FYI - In Powertool v1.3.1 

The options for Host/Tenant are always checked which is fine but now when it generates a basic UI page the list functionality doesn't work - returns 0 data in application query GetAll()

Removing interface IMayHaveTenant and the Tenant ID from the application service resolved the issue for me but my application is not multi-tenancy enabled so not sure how you would handle the scenario for others.

**Comment by ismcagdas** [comment]
@valuewholesale even if your entities implement IMayHaveTenant interface, TenantId field should contain the value 1 which is the Id of Default Tenant. 
Do you remember the values in that field ?

**Comment by valuewholesale** [comment]
Unfortunately, I do not know.  But from what I remember the DTOs did not contain anything with Tenant while the Core class did.

**Comment by ismcagdas** [comment]
@valuewholesale the DTOs shouldn't contain TenantId field since it is filled by ABP. I just tried the same scenario with the latest AspNet Zero (v5.3) and Power Tools (v1.3.2) by disabling multi tenancy. I was able to see the records that I have created.
