### ISSUE TITLE
More documents please 

### ISSUE THREAD

**Issue by hitaspdotnet** [aspnetzero/documents#58]
Between other frameworks your awesome features **Multi-Tenancy**, **Modular Design** and **Plugin System** is wonderful. I don't know why your customers haven't good articles about these like Multi-Tenancy articles. 
It is entirely true that the ABP and there Template's is based on the Module System and all the documentation is available for that, but in the Plugin section only a few document lines can be used.
For sample if a module had some special resources like ".cshtml files, .css, etc" how we can use them without hard codes in controllers. I cant find any docs about this! just found about module controller's.

**Comment by ismcagdas** [comment]
@hitaspdotnet thank you for your suggestion. We will try to create tutorials about such use cases.
