### ISSUE TITLE
Rad Tool File Path Needs To Be Documented

### ISSUE THREAD

**Issue by SteveArr** [aspnetzero/documents#59]
In order to customize the Rad Tool, you have to edit some files where the Rad Tool is installed.  The path to the Rad Tool is unknown and not described in the documentation.  

> The templates are inside "/AspNetZeroRadTool/FileTemplates" directory. 

Where is this /AspnetZeroRadTool folder?

**Comment by ismcagdas** [comment]
@SteveArr the folder "AspnetZeroRadTool" must be localed next to src, packages and test folders in the root directory of your solution. See below screenshot;

![image](https://user-images.githubusercontent.com/4133525/37327402-320a62f4-26a7-11e8-8c98-c9aeaba04d4c.png)

@yekalkan is there any reference to the location of AspnetZeroRadTool folder in our documents ?

**Comment by yekalkan** [comment]
@ismcagdas No, but i'm not sure it should be.

**Comment by SteveArr** [comment]
Made the change in the documentation and have a pull request open.

https://github.com/aspnetzero/documents/pull/64
