### ISSUE TITLE
RAD Tutorials

### ISSUE THREAD

**Issue by RodrigoSturm** [aspnetzero/documents#61]
We need more tutorials about RAD, some topics:

- How to manualy add new Primitive/Navigation properties after created a new entity.
- How to use a enum property
- How to create a new Menu position

**Comment by yekalkan** [comment]
> How to create a new Menu position

That feature doesn't not exist for now, but in our future plans.

> How to use an enum property

Choose 'enum' in property type list. Then it will get a list of enums in solution. Pick your enum.

> How to manualy add new Primitive/Navigation properties after created a new entity.

Create a new entity with exactly same namespace, table name, entity name and plural entity name. Uncheck add-migartion and update-database. Then add your all primitive and navigation properties. Tool will override the existing files. You have to manually run add-migration and update-database. We'll provide a better way to do this in next releases. This should be on documentation as you say.

We are planning add a new short video tutorial as well.

**Comment by RodrigoSturm** [comment]
Thanks a lot!
