### ISSUE TITLE
saat sorunları

### ISSUE THREAD

**Issue by mersahin** [aspnetzero/documents#70]
saatlerle ilgili genel olarak ufak tefek hatalar görülüyor bi elden geçirilmesi gerekebilir.
global kullanıcılarda sorunlara sebep olabilir. 

bir örnek giriş yapılmış; bilgisi 2 saat sonra giriş yapacak şeklinde görünüyor.
![image](https://user-images.githubusercontent.com/3853524/37827616-82875bee-2e98-11e8-9061-1a52b348294a.png)

**Comment by ismcagdas** [comment]
Moved to https://github.com/aspnetzero/aspnet-zero-core/issues/950

**Comment by ismcagdas** [comment]
@mersahin thanks a lot for your report.
