### ISSUE TITLE
Power Tool Enum Generate Sonu

### ISSUE THREAD

**Issue by ridvanozbugru** [aspnetzero/documents#74]
Merhaba power tool da enum type olan tablolarımız da generate viewlerin index viewlerini oluşturmuyor.Ekte oluşturduğu ekran mevcut bir kaç kez denedik ama olmadı.
 
![ekran alintisi](https://user-images.githubusercontent.com/8488300/39526557-cde6cd96-4e27-11e8-9c28-191e2340c5ba.PNG)

**Comment by yekalkan** [comment]
I couldn't reproduce it.

 Is there any error on console? (like "couldn't generate index.js")

**Comment by ridvanozbugru** [comment]
hayır consolda herhangi bir hata oluşmuyor.

**Comment by ridvanozbugru** [comment]
index.js generate etmiş

**Comment by yekalkan** [comment]
Does error only occurs when you have an enum property?

**Comment by ridvanozbugru** [comment]
Evet yalnızca enum alan varken aldım bu hatayı diğer alanlarda herhangi generatelerde sorun yaşamadım.

**Comment by yekalkan** [comment]
Sıfırdan oluşturduğum bir proje üzerinde enum'ı olan bir entity yarattım fakat bir hata almadım veya eksik bir dosya görmedim. index.cshtml'in oluşmasını engelleyecek bir hata olması durumunda "warning" ile başlayan bir hata mesajı yazması gerekiyor.

Projenizin altında "AspNetZeroRadTool\FileTemplates\Client\Mvc\IndexHtmlTemplate" klasörü var mı?
