### ISSUE TITLE
RAD tool latest documentation and Features

### ISSUE THREAD

**Issue by raasforce** [aspnetzero/documents#76]
Can you generate a quick document about the RAD tool, it has a lot of good features, but mentioned in the documentation. 
- 5.4 seems to add many features to RAD tool, please work on a document to guide us better.

**Comment by hikalkan** [comment]
We will add info to https://aspnetzero.com/Documents/Development-Guide-Rad-Tool for new features just after the AspNet Zero v5.4.0 release.

**Comment by yekalkan** [comment]
https://github.com/aspnetzero/documents/pull/77
