### ISSUE TITLE
Modify URL in asp.net zero

### ISSUE THREAD

**Issue by AhsanNissar** [aspnetzero/documents#85]
I have different tenants name and a login page whose path is localhost:4200/account/login but before that i have localhost:4200/account/workspace page where i will enter my tenantName in a textbox and the particular tenantId will be in the cookies. Now i want my next login page url to be like this  localhost:4200/tenantName/account/login and even after login i want the tenantName exactly there throughout the whole session. I am new to this and completely stuck here for 2 days. How can i modify my url here? This is problem is almost similar to this problem here.

[https://forums.asp.net/t/2127416.aspx?](url)
The difference is that i have to make changes in my front-end and not in the backend and its asp.net zero not asp.net core. Here is the code for my root-routing module file.

` import { NgModule } from '@angular/core';
 import { Routes, RouterModule } from '@angular/router';

 const routes: Routes = [
{ path: '', redirectTo: '/app/home', pathMatch: 'full' },
{
    path: 'account',
    loadChildren: 'account/account.module#AccountModule', //Lazy load account module
    data: { preload: true }
},
{
    path: 'app',
    loadChildren: 'app/app.module#AppModule', //Lazy load account module
    data: { preload: true }
}

];

@NgModule({
imports: [RouterModule.forRoot(routes)],
exports: [RouterModule],
providers: [] 
})
export class RootRoutingModule { }`

**Comment by ismcagdas** [comment]
@AhsanNissar we are also not sure how to do it. This is an Angular routing usage problem.
Also, please create your further issues on https://github.com/aspnetzero/aspnet-zero-core/issues.
