### ISSUE TITLE
while upgrade angular 6 + rxjs 6 and abp-ng2-module

### ISSUE THREAD

**Issue by JigneshPatel04** [aspnetzero/documents#86]
I didn't login in my project because didn't get a proper response.
below link description in it.
https://github.com/aspnetboilerplate/abp-ng2-module/issues/30#issuecomment-396134784

**Comment by ismcagdas** [comment]
@JigneshPatel04 this is related to documentation and open to public. Please open your issue on https://github.com/aspnetzero/aspnet-zero-core/issues. If you don't have access to private repositories, send your AspNet Zero username via email to info@aspnetzero.com.

**Comment by JigneshPatel04** [comment]
do you mean this link https://github.com/aspnetzero/documents/tree/master/doc

**Comment by ismcagdas** [comment]
No.

https://github.com/aspnetzero/aspnet-zero-core/issues

**Comment by JigneshPatel04** [comment]
ok, but it is not open. 404 error. I have not AspNet Zero username.

**Comment by ismcagdas** [comment]
@JigneshPatel04 the codes you have shared in this issue https://github.com/aspnetboilerplate/abp-ng2-module/issues/30 is taken from AspNet Zero. So, if you don't have an AspNet Zero username, how did you find it's source code ?

This part is exactly a copy from AspNet Zero;

![image](https://user-images.githubusercontent.com/4133525/41224606-8c31e7d8-6d75-11e8-8a45-565c05c32be0.png)
