### ISSUE TITLE
abp Chrome  Mesaj Sorunu

### ISSUE THREAD

**Issue by ridvanozbugru** [aspnetzero/documents#88]
Merhaba Chrome abp.message.confirm çalışmıyor.

**Comment by ismcagdas** [comment]
@ridvanozbugru bu durum ile nerede karşılaştınız ? Eğer AspNet Zero kullanıyorsanız, sorunu https://github.com/aspnetzero/aspnet-zero-core/issues kısmından bildirebilir misiniz ?

**Comment by ridvanozbugru** [comment]
Evet asp.net zero kullanıyorum ama tüm sistemlerde almaya başladım silme yaparken delete ekranında ki kod çalışmıyor asp.net zero da boilerplate de sizin web sitenizde çalışan demo sayfasına da girdim kullanıcı sil dedim orda da çalışmadı.hata vermiyor ama message ekranı da gelmiyor.Ayrıca belirtmiş olduğunuz link 404 veriyor.Kod aşağıda 

abp.message.confirm(
                "İşleme devam etmek istediğinize emin misiniz?",
                function (isConfirmed) {
                    if (isConfirmed) {
                        _service.deleteAsync(data_id).done(function () {
                            refreshList();
                        });
                    }
                }
            );

**Comment by ridvanozbugru** [comment]
bu arada hatayı chrome da alıyorum diğer tarayıcılarda açılıyor.

**Comment by ismcagdas** [comment]
@ridvanozbugru AspNet Zero kullanıcı adınızı paylaşırsanız, size github'da yetki verelim.

**Comment by ridvanozbugru** [comment]
ridvanozbugru

**Comment by ismcagdas** [comment]
Bu GitHub kullanıcı adınız sanırım. 
aspnetzero.com'a giriş yaptığınız kullanıcı adınız gerekiyor bize.

**Comment by ismcagdas** [comment]
Teşekkürler, GitHub'dan davetiye gönderildi. Bundan sonraki sorunlarınızı daveti kabul ettikten sonra https://github.com/aspnetzero/aspnet-zero-core/issues kısmından oluşturabilirsiniz.

**Comment by ridvanozbugru** [comment]
peki buraya açtığım başlığı tekrar orayada mı açıcam bununla ilgileniyor musunuz.

**Comment by ismcagdas** [comment]
Ben şuraya taşıdım, oradan devam edebiliriz https://github.com/aspnetzero/aspnet-zero-core/issues/1289

**Comment by ridvanozbugru** [comment]
bana davetiye falan gelmedi hangi git hesabına gönderdiniz.

**Comment by ismcagdas** [comment]
Biraz gecikme olabilir. @ridvanozbugru hesabına göndredik. Şu adrese girince daveti kabul etme butonu görmeniz gerekiyor https://github.com/aspnetzero.
