### ISSUE TITLE
HTML Versions of Documentation

### ISSUE THREAD

**Issue by godrunner** [aspnetzero/documents#89]
There used to be HTML versions of the docs, but now I only see markdown.
I host my own docs for accessibility reasons (I am legally blind) and it would be nice to not have to bother to convert them. It would be nice clone the raw docs as hitml if possible.
If not I'll convert them. 
Wondering what your workflow is with these.

Thanks!!

**Comment by ismcagdas** [comment]
@godrunner we manually convert Markdown to HTML while displaying docs on our website.
We use a library called CommonMark.NET ( https://github.com/Knagis/CommonMark.NET ).

Let us see what we can do about this in the near future.

**Comment by godrunner** [comment]
@ismcagdas, I have found a few solutions that work nicely for me with this issue. 
Since I am maybe the only one who is affected by this, you can close it if you want and finish the Blazor version of Zero by next Monday if you would rather, lol. 
If there is a super easy way to post HTML versions on an ongoing basis, well, that would be cool, but don't sweat it. Thanks!!!

**Comment by ismcagdas** [comment]
@godrunner I'm glad to hear that. Then we can leave this issue open with a low priority for now but we can implement it in the future.
