### ISSUE TITLE
Update Localization welcomepage info

### ISSUE THREAD

**Issue by ashgadala** [aspnetzero/documents#95]
on the localization XML, node <text name="WelcomePage_Info"  > defaults to _Welcome!
Welcome to the **application**. You can use the menu to start using the **application**. If you don't see any menu item, probably you don't have permission to see any page. Consider to ask system administration for permissions._

I noticed that on the other nodes "application" is defaulted to project name, I updated on my end.

**Comment by leonkosak** [comment]
Maybe generic work application (instead of a real application name, which is also in .xml with translations by default).
Just guessing....
