### ISSUE TITLE
Scheduler Sorunu Hk.

### ISSUE THREAD

**Issue by ridvanozbugru** [aspnetzero/documents#97]
Merhaba Scheduler ile ilgili yazmış olduğum kod aşağıda yer almaktadır.Ancak repostory nesnesi oluşamadığı için çalışmıyor.

`public static class ScedulersExtension
    {
        public static void RunScheduler(this IServiceCollection services)
        {
            services.AddScoped<SchedulerJob, SchedulerJob>();
            JobManager.JobFactory = new SchedulerJobFactory(services);
            JobManager.Initialize(new SchedulerJobRegistry());
        }
    }
public class SchedulerJobRegistry : Registry
    {
        
        public SchedulerJobRegistry()
        { 
            Schedule<SchedulerJob>().ToRunNow().AndEvery(30).Seconds();

        }
    }
     

    public class SchedulerJobFactory : IJobFactory
    {
        private readonly IServiceProvider _serviceProvider;

        public SchedulerJobFactory(IServiceCollection services)
        {
            _serviceProvider = services.BuildServiceProvider();
           
        }

        public IJob GetJobInstance<T>() where T : IJob
        {
            return _serviceProvider.GetService<T>();
        }
    }

    public class SchedulerJob : IJob
    {
         IRepository<UserSubscriptionPlan>  _projectRepository;
        

        public SchedulerJob(IRepository<UserSubscriptionPlan> projectRepository)
        {
            _projectRepository = projectRepository;
        }

        public void Execute()
        {
            UpdateProjectStatuses();
        }

        private void UpdateProjectStatuses()
        {

            var test = _projectRepository.GetAllList();

            Action someMethod = new Action(() =>
            {

               
                Console.WriteLine("Timed Task - Will run now");

                DateTime currentDate = DateTime.Now;

                //var userPlans = _projectRepository.GetAll().Where(x => x.SubscriptionStartDate.AddDays(x.Day) < currentDate).ToList();

             //   userPlans.ForEach(u => u.IsActive = false);

            });
        }

    }`

**Comment by ismcagdas** [comment]
Aldığınız hatayı da paylaşabilir misiniz ?

**Comment by ridvanozbugru** [comment]
Merhaba Hata Almıyorum çalışmıyor SchedulerJob class construct boş olursa medhot çalışıyor IRepository ile çağırırsam çalışmıyor.

**Comment by ismcagdas** [comment]
Logs.txt dosyasına (genelde App_Data klasörü altında) bir hata logu yazılıyor olmsı lazım, kontrol edebilir misiniz ?

**Comment by ridvanozbugru** [comment]
merhaba hata mesajı alamadım ama output log aşağıda ki mesajları alıyorum.
Exception thrown: 'System.InvalidOperationException' in Microsoft.Extensions.DependencyInjection.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
Exception thrown: 'System.AggregateException' in System.Private.CoreLib.dll

**Comment by ridvanozbugru** [comment]
Merhaba Durumla ilgili var mı gelişme kod doğru şekilde mi tanımlanmış mı ? Durum biraz acilde yardımcı olursanız sevinirim.

**Comment by ismcagdas** [comment]
Aldığınız mesajdan hatalı bir kullanım var gibi gözüküyor ama tam hata mesajı olmadan durumu tahmin etmek zor. SchedulerJob sınıfını nasıl kullanıyorsunuz ?

**Comment by ridvanozbugru** [comment]
Nasıl kullanıyordan kastınız nedir acaba.

**Comment by ismcagdas** [comment]
Yani bu sınıftan bir instance'ı nasıl oluşturuyorsunuz ? Hangfire mı kullanıyorsunuz ?

**Comment by ridvanozbugru** [comment]
aslında yukarda jobfactory de yapıyordum ama siz hangfire deyinde onu denedim bir de onda aşağıda ki şekilde bir hata alıyorum.Bir de app servis kullandığımda auth hatası alıyorum onu nasıl aşabilirim.

```
System.ObjectDisposedException
Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances. Object name: 'SubscribaTestDbContext'.

System.ObjectDisposedException: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'SubscribaTestDbContext'.
   at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)
   at SubscribaTest.Web.Mvc.Controllers.MyJobsController.JobEsy() in  \Controllers\MyJobsController.cs:line 37
```

**Comment by ismcagdas** [comment]
Burada unitOfWork dışında DbContext'e erişim sağlıyorsunuz sanırım.
Kodunuzu aşağıdaki linkteki örneğe benzer şekilde bir unitOfWork scope içerisine alırsanız bu hatayı geçebilirsiniz.

https://aspnetboilerplate.com/Pages/Documents/Unit-Of-Work#iunitofworkmanager

**Comment by ridvanozbugru** [comment]
peki appservis çağırdığımda auth problemini nasıl aşabilirim

**Comment by ismcagdas** [comment]
Onun için https://forum.aspnetboilerplate.com/viewforum.php?f=5 adresinde bir başlık açabilir misiniz ? Normalde buradan destek vermiyoruz. 

Bir de soruyu foruma gönderirken ingilizce yazarsanız iyi olur çünkü ana dili Türkçe olmayan ve destek veren birkaç arkadaşımız var, büyük ihtimalle size onlar yardımcı olacaktır.
