### ISSUE TITLE
MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled. hk.

### ISSUE THREAD

**Issue by enversalih** [aspnetzero/documents#98]
Merhaba, 

asp.net core 2 + jquery versiyonda IIS sunucuda deploy sonrasında aşağıdaki hatayı alıyorum. Aynı durum geliştirme sırasında VS üzerinde yer almıyor. 

`Refused to apply style from 'http://default.xxx.com/Error?statusCode=404' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

**Comment by ismcagdas** [comment]
Merhaba,

Normalde bu kısımdan destek vermiyoruz.
Sorunuzu https://forum.aspnetboilerplate.com/viewforum.php?f=5 adresine browser network tabının ekran görüntüsünü de ekleyerek sorabilir misiniz ?

Ekren görüntüsünde bu hatayı aldığınız request'den bir önceki request hatanın asıl sebebi olabilir.
