### ISSUE TITLE
VSTS (and TFS) continuous integration, building and deploying (IIS)

### ISSUE THREAD

**Issue by leonkosak** [aspnetzero/documents#99]
Documentation for setting up VSTS or TFS for continuous integration. Maybe something like Step-by-step tutorial for developing an application.
Some of "steps" besides just building an app, which are optional in continuous integration "pipeline":

- code signing (certificate)
- code obfuscation
- setting up new version number for or assemblies,... and application
- running unit test (and TestCafe?)
- keeping secret data (connection strings, passwords,...) in VSTS/TFS and not directly in files - the right configuration data for specific environment and customer are safer in encrypted "store" - in case of a successful hacker attack on login in a production system
hint for Azure: https://stormpath.com/blog/store-protect-sensitive-data-dotnet-core
what about .NET Core on local IIS?
- secure deploy (SFTP) to Azure
- automatic deploy of new production-ready version (with right configuration files) - both API and web app

I know that Azure deployment document is already done, but manually building on a developer machine and manually changing config files are not a preferred way of doing this.

Releasing a robust production-ready application version is not just good coding or unit testing. Less manual work during building and deploying, fewer mistakes can be made.

This tutorial would greatly help developers setting up building end deployment environments.

**Comment by ismcagdas** [comment]
@leonkosak Thanks, we will consider this for the next releases.
